#!/bin/python3

import math
import os
import random
import re
import sys
import heapq

#
# Complete the 'cookies' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER k
#  2. INTEGER_ARRAY A
#

def cookies(k, A):
    # Write your code here
    c=0
    heapq.heapify(A)
    while (A[0]<k) and len(A)>=2:
        s1=heapq.heappop(A)
        s2=heapq.heappop(A)
        sweatness=(1*s1)+(2*s2)
        heapq.heappush(A,sweatness)
        c+=1
    if A[0]<k and len(A)==1:
        return -1
    return c
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    k = int(first_multiple_input[1])

    A = list(map(int, input().rstrip().split()))

    result = cookies(k, A)

    fptr.write(str(result) + '\n')

    fptr.close()
