#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'superReducedString' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def superReducedString(s):
    # Write your code here
    lst=[]
    for i in s:
        if len(lst)==0:
            lst.append(i)
        elif i==lst[-1]:
            lst.pop()
        else:
            lst.append(i)
    if len(lst)==0:
        return "Empty String"
    else:
        return "".join(lst)
            
                
                

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = superReducedString(s)

    fptr.write(result + '\n')

    fptr.close()
